language: c  # Not really, but Travis doesn't do OCaml.

env:
  - PPA="avsm/ocaml40+opam11" OPAMYES="1"
  - PPA="avsm/ocaml41+opam11" OPAMYES="1"

before_install:
  - "echo 'yes' | sudo add-apt-repository ppa:$PPA"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam"
  - "opam init"
  - "eval `opam config env`"

install:
  - "opam install lwt lwt.unix xmlm ounit"

script:
  - "ocaml setup.ml -configure --enable-tests"
  - "make"
  - "make test"
